springdoc:
  swagger-ui:
    path: /swagger-ui.html
#  api-docs:
#    enabled: true
#    version: "openapi_3_0"
spring:
  application:
    name: event-source-service
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        output-out-0:
          destination: http-messages
      kafka:
        binder:
          brokers: localhost:9092 # Adjust if needed
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer