#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  writer-with-default-pretty-printer: true
#  api-docs:
#    enabled: true
#    version: "openapi_3_0"
spring:
  application:
    name: web-service
