apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: filtering-standard-account-sink
    run:  filtering-standard-account-sink
  name:  filtering-standard-account-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  filtering-standard-account-sink
  template:
    metadata:
      labels:
        name:  filtering-standard-account-sink
    spec:
      containers:
        - env:
            - name: spring.application.name
              value: filtering-standard-account-sink
            - name: account.type
              value: standard
            - name: spring.data.redis.host
              value: valkey-primary
            - name: spring.rabbitmq.host
              value: rabbitmq
            - name: spring.rabbitmq.stream.host
              value: rabbitmq
            - name: server.port
              value: "8080"
            - name: spring.rabbitmq.username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: spring.cloud.stream.bindings.output.destination
              value: "showcase.event.filter.streaming.accounts"
          image: cloudnativedata/filtering-account-sink:0.0.1-SNAPSHOT
          name: filtering-account-sink
#          imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: filtering-account-sink
spec:
  selector:
    name: filtering-account-sink
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer